#!/usr/bin/env python3 

import boto3

s3 = boto3.client('s3', region_name='us-east-1')

bucket = 'ds2022-vwr6nd'
local_file = '/Users/taraghose/Desktop/download.jpg'
object_name = 'lab4_file2.jpg'

resp = s3.put_object(
    Body = open(local_file,'rb'),
    Bucket = bucket,
    Key = local_file,
    ACL = 'public-read',
    ContentType='image/jpeg'
)

expires_in = 604800

response = s3.generate_presigned_url(
    'get_object',
    Params={'Bucket': bucket, 'Key': local_file},
    ExpiresIn=expires_in,
    )

print(response)

https://ds2022-vwr6nd.s3.amazonaws.com//Users/taraghose/Desktop/download.jpg?AWSAccessKeyId=AKIAYLZZJU7V7BD2LT2G&Signature=NVI1vo0nXIcqsipF5YVkDvzNRZc%3D&Expires=1728333952
