#!/bin/bash

apt update -y
apt upgrade -y

apt install -y python3 python3-pip

apt install -y python3 python3-pip
pip3 install --user awscli --upgrade
pip3 install --user pandas
pip3 install --user boto3

